#!/bin/bash
# SyntaxBridge Project Map Generator
# Generates a structural map of the project for efficient LLM navigation.

set -e

# Default to current directory if no argument provided
SEARCH_DIR="${1:-.}"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

SWIFT_TOOL="$SCRIPT_DIR/swift-summarizer/.build/release/swift-summarizer"
OBJC_TOOL="$SCRIPT_DIR/objc-summarizer-v2.py"

echo "# Project Structure Map"
echo "Generated by SyntaxBridge"
echo ""

# Find all relevant files
find "$SEARCH_DIR" -type f \( -name "*.swift" -o -name "*.m" -o -name "*.h" \) -not -path "*/.*" -not -path "*/build/*" | sort | while read -r FILE; do
    
    # Skip the tools directory itself to avoid noise, unless it's in a Sources folder
    if [[ "$FILE" == *"/tools/"* ]] && [[ "$FILE" != *"/Sources/"* ]]; then
        continue
    fi

    REL_PATH=${FILE#$SEARCH_DIR/}
    # Remove leading slash if present
    REL_PATH=${REL_PATH#/}
    
    echo "## $REL_PATH"
    
    if [[ "$FILE" == *.swift ]]; then
        if [ -f "$SWIFT_TOOL" ]; then
            # Run swift tool and parse JSON output using python (to avoid jq dependency)
            "$SWIFT_TOOL" --map "$FILE" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    symbols = data.get('symbols', [])
    for s in symbols:
        name = s.get('name', '')
        type_ = s.get('type', '')
        line = s.get('line', 0)
        
        icon = '🔹'
        if type_ == 'class': icon = '📦'
        elif type_ == 'struct': icon = '🏗️'
        elif type_ == 'enum': icon = '🔢'
        elif type_ == 'protocol': icon = '📜'
        elif type_ == 'extension': icon = '➕'
        elif type_ == 'function': icon = 'ƒ'
        
        if type_ != 'function': # Show high-level types primarily
            print(f'- {icon} [{type_}] {name}')
except:
    pass
"
        fi
    elif [[ "$FILE" =~ \.(m|h)$ ]]; then
        if [ -f "$OBJC_TOOL" ]; then
             python3 "$OBJC_TOOL" --map "$FILE" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    symbols = data.get('symbols', [])
    for s in symbols:
        name = s.get('name', '')
        type_ = s.get('type', '')
        
        icon = '🔹'
        if type_ == 'interface': icon = '📦'
        elif type_ == 'implementation': icon = '⚙️'
        elif type_ == 'protocol': icon = '📜'
        elif type_ == 'method': icon = 'ƒ'
        
        if type_ != 'method': # Show high-level types primarily
            print(f'- {icon} [{type_}] {name}')
except:
    pass
"
        fi
    fi
    echo ""
done
